version: 2

sources:
  - name: bronze
    schema: "{{ env_var('AXIOMATIC_SCHEMA_BRONZE', 'bronze') }}"
    tables:
      - name: products
      - name: users
      - name: carts
      - name: carts__products
