"""
Unit tests for axiomatic_engine.cli.staging_generator.

Tests cover:
- to_snake_case: naming edge cases
- _resolve_cast: type mapping and ambiguity flagging
- generate_staging_sql: end-to-end SQL output contract
"""
from __future__ import annotations

import pytest

from axiomatic_engine.cli.staging_generator import (
    _resolve_cast,
    generate_staging_sql,
    to_snake_case,
)
from axiomatic_engine.contracts.warehouse import ColumnInfo


class TestToSnakeCase:
    def test_simple_space_separated(self) -> None:
        assert to_snake_case("Commissioner Org Code") == "commissioner_org_code"

    def test_leading_digit_moved_to_end(self) -> None:
        result = to_snake_case("0 To 1 Weeks SUM 1")
        assert not result[0].isdigit(), f"Should not start with digit: {result}"

    def test_already_snake(self) -> None:
        assert to_snake_case("already_snake") == "already_snake"

    def test_dlt_prefix_preserved(self) -> None:
        assert to_snake_case("_dlt_load_id") == "_dlt_load_id"

    def test_multiple_underscores_collapsed(self) -> None:
        result = to_snake_case("col__name  test")
        assert "__" not in result

    def test_special_chars_stripped(self) -> None:
        result = to_snake_case("Col (Units) %")
        assert "(" not in result
        assert "%" not in result

    def test_mixed_case(self) -> None:
        assert to_snake_case("PeriodDate") == "perioddate"

    def test_all_digits(self) -> None:
        result = to_snake_case("123")
        assert result and not result[0].isdigit()

    def test_empty_after_strip(self) -> None:
        result = to_snake_case("---")
        assert result != ""


class TestResolveCast:
    def test_varchar(self) -> None:
        cast_type, ambiguous = _resolve_cast("VARCHAR")
        assert cast_type == "varchar"
        assert not ambiguous

    def test_integer(self) -> None:
        cast_type, ambiguous = _resolve_cast("INTEGER")
        assert cast_type == "integer"
        assert not ambiguous

    def test_bigint(self) -> None:
        cast_type, ambiguous = _resolve_cast("BIGINT")
        assert cast_type == "bigint"
        assert not ambiguous

    def test_date(self) -> None:
        cast_type, ambiguous = _resolve_cast("DATE")
        assert cast_type == "date"
        assert not ambiguous

    def test_timestamp(self) -> None:
        cast_type, ambiguous = _resolve_cast("TIMESTAMP")
        assert cast_type == "timestamp"
        assert not ambiguous

    def test_boolean(self) -> None:
        cast_type, ambiguous = _resolve_cast("BOOLEAN")
        assert cast_type == "boolean"
        assert not ambiguous

    def test_json_is_ambiguous(self) -> None:
        cast_type, ambiguous = _resolve_cast("JSON")
        assert ambiguous

    def test_struct_is_ambiguous(self) -> None:
        cast_type, ambiguous = _resolve_cast("STRUCT(x INT)")
        assert ambiguous

    def test_unknown_type_is_ambiguous(self) -> None:
        cast_type, ambiguous = _resolve_cast("COMPLETELY_UNKNOWN_TYPE")
        assert ambiguous

    def test_decimal_prefix(self) -> None:
        cast_type, ambiguous = _resolve_cast("DECIMAL(10, 2)")
        assert cast_type == "decimal"
        assert not ambiguous


class TestGenerateStagingSql:
    def _basic_columns(self) -> list[ColumnInfo]:
        return [
            ColumnInfo(name="Period", data_type="DATE", is_nullable=True),
            ColumnInfo(name="Commissioner Org Code", data_type="VARCHAR", is_nullable=True),
            ColumnInfo(name="0 To 1 Weeks SUM 1", data_type="INTEGER", is_nullable=True),
            ColumnInfo(name="_dlt_load_id", data_type="VARCHAR", is_nullable=False),
            ColumnInfo(name="_dlt_id", data_type="VARCHAR", is_nullable=False),
        ]

    def test_output_contains_header_comment(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        assert "auto-generated by axiomatic-engine generate-staging" in sql

    def test_output_contains_config_block(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        assert "{{ config(" in sql
        assert "env_var('AXIOMATIC_SCHEMA_SILVER', 'silver')" in sql

    def test_output_contains_from_source(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        assert "from {{ source('my_source', 'my_table') }}" in sql

    def test_dlt_metadata_excluded_from_data_columns(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        assert "_dlt_id" not in sql

    def test_load_id_aliased(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        assert "as load_id" in sql

    def test_snake_case_alias_applied(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        assert "as commissioner_org_code" in sql

    def test_date_column_rendered(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        assert '"Period"' in sql
        assert "as period" in sql

    def test_ambiguous_column_flagged_with_todo(self) -> None:
        cols = [
            ColumnInfo(name="Metadata", data_type="JSON", is_nullable=True),
        ]
        sql = generate_staging_sql(
            source_name="s",
            table_name="t",
            columns=cols,
        )
        assert "-- TODO: verify type" in sql

    def test_no_todo_for_clean_columns(self) -> None:
        cols = [
            ColumnInfo(name="OrgCode", data_type="VARCHAR", is_nullable=True),
        ]
        sql = generate_staging_sql(
            source_name="s",
            table_name="t",
            columns=cols,
        )
        select_body = sql.split("select", 1)[1]
        assert "TODO" not in select_body

    def test_last_select_line_has_no_trailing_comma(self) -> None:
        sql = generate_staging_sql(
            source_name="my_source",
            table_name="my_table",
            columns=self._basic_columns(),
        )
        lines = sql.splitlines()
        from_line_idx = next(i for i, l in enumerate(lines) if l.startswith("from "))
        last_select_line = lines[from_line_idx - 1].rstrip()
        assert not last_select_line.endswith(","), f"Trailing comma on: {last_select_line!r}"

    def test_custom_silver_schema_env_var(self) -> None:
        sql = generate_staging_sql(
            source_name="s",
            table_name="t",
            columns=[ColumnInfo(name="id", data_type="INTEGER")],
            silver_schema_env_var="MY_SILVER",
            silver_schema_default="my_silver",
        )
        assert "env_var('MY_SILVER', 'my_silver')" in sql
