fake_store:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('AXIOMATIC_WAREHOUSE_PATH', './data/warehouse.duckdb') }}"
      schema: "{{ env_var('AXIOMATIC_WAREHOUSE_SCHEMA', 'bronze') }}"
      threads: 4
