"""
Bronze-to-silver staging SQL generator.

Pure functions — no I/O, no warehouse calls.  The CLI command owns those.
"""
from __future__ import annotations

import re

from axiomatic_engine.contracts.warehouse import ColumnInfo

_DLT_PREFIX = "_dlt_"
_LOAD_ID_COL = "_dlt_load_id"
_ID_COL = "_dlt_id"

_AMBIGUOUS_TYPES: frozenset[str] = frozenset(
    {
        "blob",
        "json",
        "hugeint",
        "interval",
        "list",
        "map",
        "struct",
        "union",
        "unknown",
    }
)

_TYPE_CAST_MAP: dict[str, str] = {
    "varchar": "varchar",
    "text": "varchar",
    "char": "varchar",
    "string": "varchar",
    "integer": "integer",
    "int": "integer",
    "int4": "integer",
    "int32": "integer",
    "bigint": "bigint",
    "int8": "bigint",
    "int64": "bigint",
    "hugeint": "bigint",
    "smallint": "smallint",
    "int2": "smallint",
    "tinyint": "tinyint",
    "int1": "tinyint",
    "ubigint": "bigint",
    "uinteger": "integer",
    "usmallint": "smallint",
    "utinyint": "smallint",
    "float": "float",
    "float4": "float",
    "real": "float",
    "double": "double",
    "float8": "double",
    "decimal": "decimal",
    "numeric": "decimal",
    "boolean": "boolean",
    "bool": "boolean",
    "bit": "boolean",
    "date": "date",
    "time": "time",
    "timestamp": "timestamp",
    "timestamp with time zone": "timestamp with time zone",
    "timestamptz": "timestamp with time zone",
    "timestamp_s": "timestamp",
    "timestamp_ms": "timestamp",
    "timestamp_ns": "timestamp",
}


def to_snake_case(name: str) -> str:
    """
    Convert an arbitrary column name to snake_case.

    Examples
    --------
    "Commissioner Org Code"   -> "commissioner_org_code"
    "0 To 1 Weeks SUM 1"      -> "weeks_0_to_1"  (leading digit stripped)
    "already_snake"           -> "already_snake"
    "__dlt_load_id"           -> "__dlt_load_id"  (leading underscores preserved)
    """
    if name.startswith("_"):
        return name

    lower = name.strip().lower()
    snake = re.sub(r"[^a-z0-9]+", "_", lower).strip("_")

    if snake and snake[0].isdigit():
        parts = snake.split("_")
        digit_parts = []
        word_parts = []
        for part in parts:
            if part and part[0].isdigit():
                digit_parts.append(part)
            else:
                word_parts.append(part)
        reordered = "_".join(word_parts + digit_parts).strip("_")
        snake = reordered if reordered and not reordered[0].isdigit() else f"col_{snake}"

    return snake or "unnamed"


def _resolve_cast(data_type: str) -> tuple[str, bool]:
    """
    Return (sql_cast_type, is_ambiguous).

    is_ambiguous=True when the engine cannot confidently infer the SQL type
    and wants to flag it for human review.
    """
    normalised = data_type.strip().lower()

    for prefix in _AMBIGUOUS_TYPES:
        if normalised.startswith(prefix):
            return ("varchar", True)

    mapped = _TYPE_CAST_MAP.get(normalised)
    if mapped:
        return (mapped, False)

    for key, cast_type in _TYPE_CAST_MAP.items():
        if normalised.startswith(key):
            return (cast_type, False)

    return ("varchar", True)


def _is_dlt_metadata(col: ColumnInfo) -> bool:
    return col.name.startswith(_DLT_PREFIX)


def generate_staging_sql(
    *,
    source_name: str,
    table_name: str,
    columns: list[ColumnInfo],
    silver_schema_env_var: str = "AXIOMATIC_SCHEMA_SILVER",
    silver_schema_default: str = "silver",
) -> str:
    """
    Generate a dbt staging model SQL string from a list of ColumnInfo.

    Parameters
    ----------
    source_name:
        The dbt source name (matches ``source:`` → ``name:`` in pipeline.yml).
    table_name:
        The bronze table name (matches the resource name).
    columns:
        Columns returned by warehouse introspection.
    silver_schema_env_var:
        Environment variable name for the silver schema.
    silver_schema_default:
        Default value used when the env var is not set.
    """
    lines: list[str] = []

    lines.append("-- auto-generated by axiomatic-engine generate-staging")
    lines.append("-- Review before committing. Flagged columns marked with TODO.")
    lines.append(
        "{{ config(materialized='view',"
        f" schema=env_var('{silver_schema_env_var}', '{silver_schema_default}')) }}"
    )
    lines.append("")
    lines.append("select")

    data_cols = [c for c in columns if not _is_dlt_metadata(c)]
    load_id_col = next((c for c in columns if c.name == _LOAD_ID_COL), None)

    select_parts: list[str] = []

    for col in data_cols:
        alias = to_snake_case(col.name)
        cast_type, is_ambiguous = _resolve_cast(col.data_type)
        quoted_src = f'"{col.name}"'

        if cast_type == col.data_type.lower() or cast_type == col.data_type:
            expr = quoted_src
        else:
            expr = f"cast({quoted_src} as {cast_type})"

        todo = "  -- TODO: verify type" if is_ambiguous else ""
        pad = 42
        lhs = f"    {expr}"
        if len(lhs) < pad:
            lhs = lhs.ljust(pad)
        select_parts.append(f"{lhs} as {alias}{todo}")

    if load_id_col:
        pad = 42
        lhs = f"    {_LOAD_ID_COL}"
        if len(lhs) < pad:
            lhs = lhs.ljust(pad)
        select_parts.append(f"{lhs} as load_id")

    for i, part in enumerate(select_parts):
        comma = "," if i < len(select_parts) - 1 else ""
        lines.append(f"{part}{comma}")

    lines.append(f"from {{{{ source('{source_name}', '{table_name}') }}}}")
    lines.append("")

    return "\n".join(lines)
